### PR TITLE
Add leftInset property

### PR DESCRIPTION
**Pull request by phatmann**
Currently when `centeredHorizontally` is set to false. the presented view's left offset is not set, leaving it in an essentially random horizontal position. This PR adds a `leftInset` property, and uses this property if  `centeredHorizontally` is false.

### CODE REVIEW

**Comment by m1entus** [comment]
It is already set using transition animation.

**Comment by phatmann** [comment]
When using the SlideFromLeft animation, the view ends up off-screen on the left. So maybe the fix should be in the animation code?

**Comment by m1entus** [comment]
You need to create your custom animation for example CustomSlideFromLeft and then set final frame to frame what you want.

**Comment by phatmann** [comment]
If you use the SlideFromLeft animation and centerHorizontally is false, the view ends up partially offscreen. Surely that is a bug that we need to fix..

**Pull request closed without merging**
